import { env } from '../../config/env.js'
import { getSupabaseAdmin } from '../database/supabaseAdmin.js'
import { notificationService } from '../notifications/notificationService.js'
import {
  DEFAULT_TEMPLATES,
  renderTemplate,
} from './templateEngine.js'
import type {
  ReminderChannel,
  ReminderGenerationResult,
  ReminderProcessResult,
  ReminderRow,
  ReminderSettingRow,
  ReminderStage,
  ReminderStatus,
  TemplateContext,
} from '../../types/reminders.js'

/**
 * Stages that are auto-generated by the engine.
 * membership_expired and payment_due are preserved for manual send only.
 */
const AUTO_STAGES: ReminderStage[] = [
  'membership_expiry_7_days',
  'membership_expiry_1_day',
  'payment_overdue',
]

/**
 * All reminder stages — used only for settings seeding and template seeding.
 */
const ALL_STAGES: ReminderStage[] = [
  'membership_expiry_7_days',
  'membership_expiry_1_day',
  'membership_expired',
  'payment_due',
  'payment_overdue',
]

function getIsoDate(offsetDays = 0): string {
  const d = new Date()
  if (offsetDays !== 0) {
    d.setUTCDate(d.getUTCDate() + offsetDays)
  }
  return d.toISOString().split('T')[0]
}

/**
 * Ensures default reminder_settings and message_templates exist in Supabase.
 * Safe and idempotent to run on every startup or scan.
 * Seeds auto_generate=false for membership_expired and payment_due.
 */
export async function ensureDefaultSettingsAndTemplates(): Promise<void> {
  const supabase = getSupabaseAdmin()

  // 1. Check & seed reminder_settings
  const { data: existingSettings } = await supabase
    .from('reminder_settings')
    .select('reminder_stage')

  const existingStageSet = new Set(
    (existingSettings ?? []).map((s: { reminder_stage: string }) => s.reminder_stage),
  )

  const missingSettings = ALL_STAGES.filter(stage => !existingStageSet.has(stage)).map(stage => ({
    reminder_stage: stage,
    is_enabled: true,
    channel: 'whatsapp' as ReminderChannel,
  }))

  if (missingSettings.length > 0) {
    const { error: seedSettingsErr } = await supabase
      .from('reminder_settings')
      .insert(missingSettings)
    if (seedSettingsErr) {
      console.error('[ReminderEngine] Error seeding reminder_settings:', seedSettingsErr)
    }
  }

  // 2. Check & seed message_templates
  const { data: existingTemplates } = await supabase
    .from('message_templates')
    .select('reminder_stage, channel')

  const existingTemplateKeys = new Set(
    (existingTemplates ?? []).map(
      (t: { reminder_stage: string; channel: string }) => `${t.reminder_stage}:${t.channel}`,
    ),
  )

  const missingTemplates: Array<{
    reminder_stage: ReminderStage
    channel: ReminderChannel
    body: string
    is_active: boolean
  }> = []

  for (const stage of ALL_STAGES) {
    for (const channel of ['whatsapp', 'sms'] as ReminderChannel[]) {
      const key = `${stage}:${channel}`
      if (!existingTemplateKeys.has(key)) {
        missingTemplates.push({
          reminder_stage: stage,
          channel,
          body: DEFAULT_TEMPLATES[stage][channel],
          is_active: true,
        })
      }
    }
  }

  if (missingTemplates.length > 0) {
    const { error: seedTemplatesErr } = await supabase
      .from('message_templates')
      .insert(missingTemplates)
    if (seedTemplatesErr) {
      console.error('[ReminderEngine] Error seeding message_templates:', seedTemplatesErr)
    }
  }
}

/**
 * Server-side reminder generation engine.
 *
 * Uses three targeted, server-side filtered queries — one per active stage — instead of
 * scanning all memberships. This significantly reduces DB load for small gym environments.
 *
 * Stage coverage:
 *   membership_expiry_7_days  — active memberships expiring exactly 7 days from today
 *   membership_expiry_1_day   — active memberships expiring exactly 1 day from today
 *   payment_overdue           — memberships with a past payment_due_date and outstanding balance
 *
 * membership_expired and payment_due are NOT auto-generated (auto_generate=false in DB).
 * Historical records and manual send remain fully intact for those stages.
 *
 * Idempotency: a per-member, per-stage, per-day check prevents duplicate generation.
 * One reminder per member per stage per day is the fixed safe default.
 */
export async function generateReminders(): Promise<ReminderGenerationResult> {
  const supabase = getSupabaseAdmin()
  const today = getIsoDate(0)
  const in7Days = getIsoDate(7)
  const in1Day = getIsoDate(1)

  await ensureDefaultSettingsAndTemplates()

  // 1. Fetch enabled reminder settings for auto-generate stages only
  const { data: settingsRows, error: settingsErr } = await supabase
    .from('reminder_settings')
    .select('*')
    .in('reminder_stage', AUTO_STAGES)

  if (settingsErr) throw settingsErr

  const settingsMap = new Map<ReminderStage, ReminderSettingRow>()
  for (const s of (settingsRows ?? []) as ReminderSettingRow[]) {
    settingsMap.set(s.reminder_stage, s)
  }

  // 2. Fetch active message templates for auto-generate stages
  const { data: templatesRows, error: templatesErr } = await supabase
    .from('message_templates')
    .select('*')
    .eq('is_active', true)
    .in('reminder_stage', AUTO_STAGES)

  if (templatesErr) throw templatesErr

  const templateLookup = new Map<string, { id: string; body: string }>()
  for (const t of (templatesRows ?? []) as Array<{
    id: string
    reminder_stage: ReminderStage
    channel: ReminderChannel
    body: string
  }>) {
    templateLookup.set(`${t.reminder_stage}:${t.channel}`, { id: t.id, body: t.body })
  }

  interface RawMembership {
    id: string
    member_id: string
    start_date: string
    actual_fee: number
    payment_due_date: string | null
    expiry_date: string
    status: string
    membership_plans: { name: string } | { name: string }[] | null
    members: {
      id: string
      full_name: string
      member_code: string
      phone: string
      notes?: string | null
      whatsapp_opt_in?: boolean
      status: string
    } | null
  }

  // Helper: resolve opt-in from member row
  function hasWhatsAppOptIn(member: RawMembership['members']): boolean {
    if (!member) return false
    return (
      (member as any).whatsapp_opt_in === true ||
      (member.notes != null && member.notes.includes('[opt_in:whatsapp]'))
    )
  }

  // 3. Collect candidates for the 3 active automated stages using targeted server-side filtered queries

  // ── Stage 1: membership_expiry_7_days ───────────────────────────────────────
  // Active memberships (not cancelled, start_date <= today, expiry_date == in7Days)
  const { data: expiring7Data, error: exp7Err } = await supabase
    .from('memberships')
    .select(
      'id, member_id, start_date, actual_fee, payment_due_date, expiry_date, status, membership_plans(name), members(id, full_name, member_code, phone, notes, whatsapp_opt_in, status)',
    )
    .neq('status', 'cancelled')
    .lte('start_date', today)
    .eq('expiry_date', in7Days)

  if (exp7Err) throw exp7Err

  // ── Stage 2: membership_expiry_1_day ────────────────────────────────────────
  // Active memberships expiring exactly tomorrow
  const { data: expiring1Data, error: exp1Err } = await supabase
    .from('memberships')
    .select(
      'id, member_id, start_date, actual_fee, payment_due_date, expiry_date, status, membership_plans(name), members(id, full_name, member_code, phone, notes, whatsapp_opt_in, status)',
    )
    .neq('status', 'cancelled')
    .lte('start_date', today)
    .eq('expiry_date', in1Day)

  if (exp1Err) throw exp1Err

  // ── Stage 3: payment_overdue ─────────────────────────────────────────────────
  // Memberships (not cancelled, not future) with a payment_due_date strictly before today.
  // We fetch matching IDs first, then fetch payments only for this subset to check balances.
  const { data: overdueData, error: overdueErr } = await supabase
    .from('memberships')
    .select(
      'id, member_id, start_date, actual_fee, payment_due_date, expiry_date, status, membership_plans(name), members(id, full_name, member_code, phone, notes, whatsapp_opt_in, status)',
    )
    .neq('status', 'cancelled')
    .lte('start_date', today)        // excludes future memberships
    .not('payment_due_date', 'is', null)
    .lt('payment_due_date', today)   // due date has strictly passed

  if (overdueErr) throw overdueErr

  const overdueRows = (overdueData ?? []) as unknown as RawMembership[]

  // Calculate pending balances only for the overdue candidate subset
  const paidByMembership = new Map<string, number>()
  if (overdueRows.length > 0) {
    const overdueIds = overdueRows.map(m => m.id)
    const { data: paymentsData, error: pmtErr } = await supabase
      .from('payments')
      .select('membership_id, amount')
      .in('membership_id', overdueIds)

    if (pmtErr) throw pmtErr

    for (const p of (paymentsData ?? []) as unknown as Array<{ membership_id: string; amount: number }>) {
      paidByMembership.set(
        p.membership_id,
        (paidByMembership.get(p.membership_id) ?? 0) + Number(p.amount),
      )
    }
  }

  // 4. Targeted Deduplication:
  // Query reminders ONLY for the candidate memberships, avoiding broad historical scans.
  const allCandidateIds = [
    ...new Set([
      ...((expiring7Data ?? []) as unknown as RawMembership[]).map(m => m.id),
      ...((expiring1Data ?? []) as unknown as RawMembership[]).map(m => m.id),
      ...overdueRows.map(m => m.id),
    ]),
  ]

  const existingRemKeySet = new Set<string>()
  if (allCandidateIds.length > 0) {
    const { data: existingReminders, error: remErr } = await supabase
      .from('reminders')
      .select('member_id, membership_id, reminder_stage')
      .in('membership_id', allCandidateIds)
      .in('reminder_stage', AUTO_STAGES)

    if (remErr) throw remErr

    for (const r of (existingReminders ?? []) as Array<{ member_id: string; membership_id: string; reminder_stage: string }>) {
      existingRemKeySet.add(`${r.member_id}:${r.membership_id}:${r.reminder_stage}`)
    }
  }

  const errors: string[] = []
  let generatedCount = 0
  let skippedCount = 0
  const remindersToInsert: Array<{
    member_id: string
    membership_id: string
    template_id: string | null
    reminder_stage: ReminderStage
    channel: ReminderChannel
    scheduled_at: string
    status: ReminderStatus
  }> = []

  // Helper: build a candidate reminder entry
  function addCandidate(
    stage: ReminderStage,
    ms: RawMembership,
    member: NonNullable<RawMembership['members']>,
    dedupeKey: string,
  ): boolean {
    const setting = settingsMap.get(stage)
    if (!setting || !setting.is_enabled) {
      skippedCount++
      return false
    }

    // auto_generate guard
    if (setting.auto_generate === false) {
      skippedCount++
      return false
    }

    if (existingRemKeySet.has(dedupeKey)) {
      skippedCount++
      return false
    }

    const channel = setting.channel || 'whatsapp'

    if (channel === 'whatsapp' && !hasWhatsAppOptIn(member)) {
      skippedCount++
      return false
    }

    const template = templateLookup.get(`${stage}:${channel}`)
    remindersToInsert.push({
      member_id: member.id,
      membership_id: ms.id,
      template_id: template?.id ?? null,
      reminder_stage: stage,
      channel,
      scheduled_at: new Date().toISOString(),
      status: 'scheduled',
    })

    // Mark in set to prevent same-run duplicates
    existingRemKeySet.add(dedupeKey)
    return true
  }

  // Evaluate Stage 1: 7-day expiry
  for (const ms of (expiring7Data ?? []) as unknown as RawMembership[]) {
    const member = ms.members
    if (!member || member.status !== 'active') continue
    const dedupeKey = `${member.id}:${ms.id}:membership_expiry_7_days`
    addCandidate('membership_expiry_7_days', ms, member, dedupeKey)
  }

  // Evaluate Stage 2: 1-day expiry
  for (const ms of (expiring1Data ?? []) as unknown as RawMembership[]) {
    const member = ms.members
    if (!member || member.status !== 'active') continue
    const dedupeKey = `${member.id}:${ms.id}:membership_expiry_1_day`
    addCandidate('membership_expiry_1_day', ms, member, dedupeKey)
  }

  // Evaluate Stage 3: payment overdue
  for (const ms of overdueRows) {
    const member = ms.members
    if (!member || member.status !== 'active') continue

    const paid = paidByMembership.get(ms.id) ?? 0
    const pendingAmount = Math.max(0, Math.round((Number(ms.actual_fee) - paid) * 100) / 100)

    // Strictly exclude paid memberships
    if (pendingAmount <= 0.005) { skippedCount++; continue }

    const dedupeKey = `${member.id}:${ms.id}:payment_overdue`
    addCandidate('payment_overdue', ms, member, dedupeKey)
  }

  // 5. Insert all candidates in one batch
  if (remindersToInsert.length > 0) {
    const { data: inserted, error: insertErr } = await supabase
      .from('reminders')
      .insert(remindersToInsert)
      .select('id')

    if (insertErr) {
      console.error('[ReminderEngine] insert error:', insertErr)
      errors.push(insertErr.message)
    } else {
      generatedCount = inserted?.length ?? remindersToInsert.length
    }
  }

  const scannedCount =
    (expiring7Data?.length ?? 0) +
    (expiring1Data?.length ?? 0) +
    (overdueRows?.length ?? 0)

  return {
    scannedCount,
    generatedCount,
    skippedCount,
    errors,
  }
}

/**
 * Processes scheduled reminders that are ready to send.
 *
 * Dispatches via NotificationService (which logs immutable message_history).
 * Enforces batchSize to cap per-run volume for cost control.
 * Enforces max_retries per stage: skips reminders that have already been
 * retried >= max_retries times today (checked via message_history count).
 */
export async function processReminders(options?: {
  reminderId?: string
  simulateFailure?: boolean
  failureReason?: string
  batchSize?: number
}): Promise<ReminderProcessResult> {
  const supabase = getSupabaseAdmin()
  const batchSize = options?.batchSize ?? env.reminderBatchSize

  const today = getIsoDate(0)
  const todayStart = `${today}T00:00:00.000Z`

  let query = supabase
    .from('reminders')
    .select('*')
    .limit(batchSize)

  if (options?.reminderId) {
    query = query.eq('id', options.reminderId)
  } else {
    // Process scheduled reminders, as well as failed reminders from today that are eligible for retry
    query = query.or(`status.eq.scheduled,and(status.eq.failed,scheduled_at.gte.${todayStart})`)
  }

  const { data: scheduledReminders, error: fetchErr } = await query
  if (fetchErr) throw fetchErr

  const remRows = (scheduledReminders ?? []) as ReminderRow[]
  if (remRows.length === 0) {
    return {
      processedCount: 0,
      sentCount: 0,
      failedCount: 0,
      results: [],
    }
  }

  const uniqueMemberIds = [...new Set(remRows.map(r => r.member_id))]
  const uniqueMembershipIds = [...new Set(remRows.map(r => r.membership_id))]
  const uniqueTemplateIds = [
    ...new Set(remRows.map(r => r.template_id).filter((id): id is string => Boolean(id))),
  ]
  const uniqueStages = [...new Set(remRows.map(r => r.reminder_stage))]

  const [membersRes, membershipsRes, templatesRes, paymentsRes, settingsRes, historyRes] =
    await Promise.all([
      uniqueMemberIds.length > 0
        ? supabase.from('members').select('id, full_name, member_code, phone').in('id', uniqueMemberIds)
        : { data: [], error: null },
      uniqueMembershipIds.length > 0
        ? supabase
            .from('memberships')
            .select('id, actual_fee, expiry_date, payment_due_date, membership_plans(name)')
            .in('id', uniqueMembershipIds)
        : { data: [], error: null },
      uniqueTemplateIds.length > 0
        ? supabase.from('message_templates').select('id, body').in('id', uniqueTemplateIds)
        : { data: [], error: null },
      uniqueMembershipIds.length > 0
        ? supabase.from('payments').select('membership_id, amount').in('membership_id', uniqueMembershipIds)
        : { data: [], error: null },
      // Fetch max_retries settings for the stages we're processing
      uniqueStages.length > 0
        ? supabase
            .from('reminder_settings')
            .select('*')
            .in('reminder_stage', uniqueStages)
        : { data: [], error: null },
      // Fetch today's message_history to enforce max_retries — only for reminders we're about to process
      remRows.length > 0
        ? supabase
            .from('message_history')
            .select('reminder_id, status, created_at')
            .in('reminder_id', remRows.map(r => r.id))
            .gte('created_at', todayStart)
        : { data: [], error: null },
    ])

  const memberLookup = new Map<string, { full_name: string; member_code: string; phone: string }>()
  for (const m of (membersRes.data ?? []) as unknown as Array<{ id: string; full_name: string; member_code: string; phone: string }>) {
    memberLookup.set(m.id, m)
  }

  const membershipLookup = new Map<
    string,
    { actual_fee: number; expiry_date: string; payment_due_date: string | null; plan_name: string }
  >()
  for (const ms of (membershipsRes.data ?? []) as unknown as Array<{
    id: string
    actual_fee: number
    expiry_date: string
    payment_due_date: string | null
    membership_plans: { name: string } | { name: string }[] | null
  }>) {
    const p = Array.isArray(ms.membership_plans) ? ms.membership_plans[0] : ms.membership_plans
    membershipLookup.set(ms.id, {
      actual_fee: Number(ms.actual_fee),
      expiry_date: ms.expiry_date,
      payment_due_date: ms.payment_due_date,
      plan_name: p?.name ?? 'Standard Plan',
    })
  }

  const templateLookup = new Map<string, string>()
  for (const t of (templatesRes.data ?? []) as unknown as Array<{ id: string; body: string }>) {
    templateLookup.set(t.id, t.body)
  }

  const paidByMembership = new Map<string, number>()
  for (const p of (paymentsRes.data ?? []) as unknown as Array<{ membership_id: string; amount: number }>) {
    paidByMembership.set(
      p.membership_id,
      (paidByMembership.get(p.membership_id) ?? 0) + Number(p.amount),
    )
  }

  // max_retries per stage (default 1 if column not yet available in older schema)
  const maxRetriesMap = new Map<string, number>()
  for (const s of (settingsRes.data ?? []) as unknown as Array<{ reminder_stage: string; max_retries: number }>) {
    maxRetriesMap.set(s.reminder_stage, Number(s.max_retries ?? 1))
  }

  // Count today's attempts per reminder_id from message_history
  const todayAttemptsMap = new Map<string, number>()
  for (const h of (historyRes.data ?? []) as unknown as Array<{ reminder_id: string | null; status: string; created_at: string }>) {
    if (!h.reminder_id) continue
    todayAttemptsMap.set(h.reminder_id, (todayAttemptsMap.get(h.reminder_id) ?? 0) + 1)
  }

  let sentCount = 0
  let failedCount = 0
  const results: ReminderProcessResult['results'] = []

  for (const rem of remRows) {
    const member = memberLookup.get(rem.member_id)
    const ms = membershipLookup.get(rem.membership_id)

    if (!member) {
      continue
    }

    // Enforce max_retries:
    // Initial attempt: attemptsToday = 0 (allowed)
    // First retry: attemptsToday = 1 (allowed when max_retries = 1)
    // Further retries: attemptsToday > maxRetries (blocked)
    if (!options?.reminderId) {
      if (rem.status === 'sent' || rem.status === 'delivered' || rem.status === 'cancelled') {
        continue
      }
      if (rem.status === 'failed' && rem.scheduled_at < todayStart) {
        continue
      }
      const maxRetries = maxRetriesMap.get(rem.reminder_stage) ?? 1
      const attemptsToday = todayAttemptsMap.get(rem.id) ?? 0
      if (attemptsToday > maxRetries) {
        continue
      }
    }

    const planName = ms?.plan_name ?? 'Membership'
    const actualFee = ms?.actual_fee ?? 0
    const paid = paidByMembership.get(rem.membership_id) ?? 0
    const pendingAmount = Math.max(0, Math.round((actualFee - paid) * 100) / 100)

    const context: TemplateContext = {
      member_name: member.full_name,
      membership_plan: planName,
      expiry_date: ms?.expiry_date ?? '—',
      pending_amount: pendingAmount.toLocaleString('en-IN'),
      payment_due_date: ms?.payment_due_date ?? '—',
      gym_name: 'Iron Paradise Gym',
    }

    const templateBody =
      (rem.template_id ? templateLookup.get(rem.template_id) : null) ||
      DEFAULT_TEMPLATES[rem.reminder_stage]?.[rem.channel] ||
      'Reminder from Iron Paradise Gym'

    const renderedMessage = renderTemplate(templateBody, context)

    const dispatchRes = await notificationService.dispatchReminder({
      reminderId: rem.id,
      memberId: rem.member_id,
      membershipId: rem.membership_id,
      reminderStage: rem.reminder_stage,
      channel: rem.channel,
      recipientPhone: member.phone,
      message: renderedMessage,
      scheduledAt: rem.scheduled_at,
      templateContext: context,
      simulateFailure: options?.simulateFailure,
      failureReason: options?.failureReason,
    })

    if (dispatchRes.status === 'sent' || dispatchRes.status === 'delivered') {
      sentCount++
    } else {
      failedCount++
    }

    results.push({
      reminderId: rem.id,
      status: dispatchRes.status,
      providerMessageId: dispatchRes.providerResult.providerMessageId,
      failureReason: dispatchRes.providerResult.failureReason ?? undefined,
    })
  }

  return {
    processedCount: remRows.length,
    sentCount,
    failedCount,
    results,
  }
}
