import { ArrowRight, MoreHorizontal } from 'lucide-react'
import { Card } from '../components/Card'
import { DataTable } from '../components/DataTable'
import { PageHeader } from '../components/PageHeader'
import { StatCard } from '../components/StatCard'
import { StatusBadge } from '../components/StatusBadge'
import { pendingPayments, recentPayments, reminderSummary, renewals, stats } from '../services/mockData'
const Action = () => <button aria-label="More actions" className="rounded p-1 text-zinc-500 hover:bg-white/[.06] hover:text-white"><MoreHorizontal size={18}/></button>
function SectionTitle({ title, action = 'View all' }: { title: string; action?: string }) { return <div className="flex items-center justify-between px-5 py-4"><h2 className="text-base font-semibold text-white">{title}</h2><button className="flex items-center gap-1 text-xs font-semibold text-brand hover:text-red-400">{action}<ArrowRight size={14}/></button></div> }
export function DashboardPage() { return <><PageHeader title="Good morning, Alex" description="Here’s what’s happening at Iron Paradise today."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats.map(s => <StatCard key={s.label} {...s}/>)}</div><div className="mt-7 grid gap-7 xl:grid-cols-3"><Card className="xl:col-span-2"><SectionTitle title="Upcoming Renewals"/><DataTable headers={['Member','Membership Plan','Expiry Date','Days Left','Fee','Status','']}>
{renewals.map(r => <tr key={r.member}><td className="table-cell font-semibold text-white">{r.member}</td><td className="table-cell">{r.plan}</td><td className="table-cell">{r.expiry}</td><td className={`table-cell font-medium ${r.days < 0 ? 'text-red-300' : r.days <= 5 ? 'text-amber-300' : 'text-zinc-300'}`}>{r.days < 0 ? `${Math.abs(r.days)} days ago` : `${r.days} days`}</td><td className="table-cell">{r.fee}</td><td className="table-cell"><StatusBadge status={r.status}/></td><td className="table-cell"><Action/></td></tr>)}
</DataTable></Card><Card><SectionTitle title="Reminder Summary" action="Manage"/><div className="grid grid-cols-2 gap-px border-y border-white/[.07] bg-white/[.07]">{reminderSummary.map((r, i) => <div key={r.label} className="bg-panel p-5"><p className={`text-2xl font-bold ${i === 3 ? 'text-red-300' : i === 2 ? 'text-emerald-300' : 'text-white'}`}>{r.value}</p><p className="mt-1 text-xs text-zinc-400">{r.label}</p></div>)}</div><div className="p-5"><p className="text-sm font-medium text-zinc-300">Delivery rate</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/[.08]"><div className="h-full w-[87%] rounded-full bg-emerald-400"/></div><p className="mt-2 text-xs text-zinc-500">87% delivered successfully today</p></div></Card></div><div className="mt-7 grid gap-7 xl:grid-cols-2"><Card><SectionTitle title="Pending Payments"/><DataTable headers={['Member','Membership','Pending','Due Date','Status','']}>
{pendingPayments.map(p => <tr key={p.member}><td className="table-cell font-semibold text-white">{p.member}</td><td className="table-cell">{p.membership}</td><td className="table-cell font-semibold">{p.pending}</td><td className="table-cell">{p.due}</td><td className="table-cell"><StatusBadge status={p.status}/></td><td className="table-cell"><Action/></td></tr>)}
</DataTable></Card><Card><SectionTitle title="Recent Payments"/><DataTable headers={['Member','Amount','Date','Method','Status']}>
{recentPayments.map(p => <tr key={p.member}><td className="table-cell font-semibold text-white">{p.member}</td><td className="table-cell font-semibold text-emerald-300">{p.amount}</td><td className="table-cell">{p.date}</td><td className="table-cell">{p.method}</td><td className="table-cell"><StatusBadge status={p.status}/></td></tr>)}
</DataTable></Card></div></> }
